version: '3'
services:
  dev:
    build:
      context: .
    command: reflex -g dev/reflex.conf -s -- reflex -c dev/reflex.conf
    volumes:
      - "../:/develop"
    environment:
      - PORT=${PORT:-8888}
    ports:
      - ${PORT:-8888}:${PORT:-8888}

